# Generated by Django 3.2.7 on 2021-09-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
