# Generated by Django 3.2.7 on 2021-09-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210929_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='', max_length=200),
        ),
    ]
